apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        component: kube-scheduler
        tier: control-plane
    name: kube-scheduler
    namespace: kube-system
spec:
    containers:
    - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        - --config=/etc/kubernetes/scheduler-extender.yaml
        - --v=9
        image: gcr.azk8s.cn/google_containers/kube-scheduler:v1.16.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
            failureThreshold: 8
            httpGet:
                host: 127.0.0.1
                path: /healthz
                port: 10251
                scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 15
        name: kube-scheduler
        resources:
            requests:
                cpu: 100m
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
            name: kubeconfig
            readOnly: true
        - mountPath: /etc/kubernetes/scheduler-extender.yaml
            name: extender
            readOnly: true
        - mountPath: /etc/kubernetes/scheduler-extender-policy.json
            name: extender-policy
            readOnly: true
    hostNetwork: true
    priorityClassName: system-cluster-critical
    volumes:
    - hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
    name: kubeconfig
    - hostPath:
        path: /etc/kubernetes/scheduler-extender.yaml
        type: FileOrCreate
    name: extender
    - hostPath:
        path: /etc/kubernetes/scheduler-extender-policy.json
        type: FileOrCreate
    name: extender-policy
status: {}